// Friendly fictional fast-food mascot. Six variants Camila can pick from
// (burger, fries, shake, nugget, icecream, chef). All 18 wide × 22 tall.
// 4 frames each: 0 = idle1, 1 = idle2 (slight bob), 2 = wave/dance left,
// 3 = wave/dance right.
//
// All mascots share the same palette so we only register one palette.

export const mascotPalette = {
  '.': null,
  '#': '#1a1a1a',     // outline
  'B': '#c9883b',     // burger bun brown
  'b': '#a06820',     // bun shadow
  'M': '#8b4513',     // patty meat
  'G': '#22aa44',     // lettuce green
  'Y': '#ffce2e',     // fries / chef yellow
  'y': '#d99c12',     // dark yellow
  'R': '#dd2233',     // red wrapper / hat
  'r': '#a3151c',     // dark red
  'W': '#ffffff',     // shake / hat white
  'C': '#fff2c2',     // cone tan
  'c': '#caa46c',     // cone shadow
  'P': '#ffc8a0',     // skin
  'S': '#7a4a14',     // sunglasses dark
  'K': '#000000',     // pure black sunglasses
  'L': '#a3d8ff',     // light blue (shake highlight)
  'N': '#f7e5a5',     // nugget breading
  'n': '#caa86a',     // nugget shadow
  'I': '#fff5dd',     // ice-cream scoop
  'i': '#e8c98e',     // scoop shadow
  'E': '#000000',     // eye
}

// Helper: pad a row to width 18 with '.'.
const W18 = (s) => s.padEnd(18, '.')

// ---- BURGER (default) — bun + patty + lettuce + arms + legs + sunglasses ----
const burger = [
  // idle1
  [
    '..................',
    '....########......',
    '...#BBBBBBBB#.....',
    '..#BBbBBBBBBb#....',
    '..#BBBBBBBBBB#....',
    '.#GGGGGGGGGGGG#...',
    '.#KKKK##KKKK##....',  // sunglasses across the patty
    '.#MMMMMMMMMMMM#...',
    '.#MMMMMMMMMMMM#...',
    '.#BBBBBBBBBBBB#...',
    '..#BBBBBBBBBB#....',
    '...##########.....',
    '...#........#.....',
    '..#..........#....',
    '.#............#...',  // arms out
    '.#............#...',
    '..#..........#....',
    '...##.....##......',
    '...##.....##......',  // legs
    '..####...####.....',
    '..................',
    '..................',
  ],
  // idle2 — pop up 1 px
  [
    '....########......',
    '...#BBBBBBBB#.....',
    '..#BBbBBBBBBb#....',
    '..#BBBBBBBBBB#....',
    '.#GGGGGGGGGGGG#...',
    '.#KKKK##KKKK##....',
    '.#MMMMMMMMMMMM#...',
    '.#MMMMMMMMMMMM#...',
    '.#BBBBBBBBBBBB#...',
    '..#BBBBBBBBBB#....',
    '...##########.....',
    '...#........#.....',
    '..#..........#....',
    '.#............#...',
    '.#............#...',
    '..#..........#....',
    '...##.....##......',
    '...##.....##......',
    '..####...####.....',
    '..................',
    '..................',
    '..................',
  ],
  // wave-left (left arm up)
  [
    '..................',
    '....########......',
    '...#BBBBBBBB#.....',
    '..#BBbBBBBBBb#....',
    '..#BBBBBBBBBB#....',
    '.#GGGGGGGGGGGG#...',
    '.#KKKK##KKKK##....',
    '.#MMMMMMMMMMMM#...',
    '.#MMMMMMMMMMMM#...',
    '.#BBBBBBBBBBBB#...',
    '..#BBBBBBBBBB#....',
    '#..##########.....',
    '##.#........#.....',
    '.#.#.........#....',
    '...#..........#...',
    '...#..........#...',
    '...#.........#....',
    '....##....##......',
    '....##....##......',
    '...####..####.....',
    '..................',
    '..................',
  ],
  // wave-right (right arm up)
  [
    '..................',
    '....########......',
    '...#BBBBBBBB#.....',
    '..#BBbBBBBBBb#....',
    '..#BBBBBBBBBB#....',
    '.#GGGGGGGGGGGG#...',
    '.#KKKK##KKKK##....',
    '.#MMMMMMMMMMMM#...',
    '.#MMMMMMMMMMMM#...',
    '.#BBBBBBBBBBBB#...',
    '..#BBBBBBBBBB#....',
    '...##########..#..',
    '...#........#.##..',
    '..#.........#.#...',
    '.#..........#.....',
    '.#..........#.....',
    '..#........#......',
    '...##....##.......',
    '...##....##.......',
    '..####..####......',
    '..................',
    '..................',
  ],
].map(rows => rows.map(W18))

// ---- FRIES ----
const fries = [
  [
    '...YYYYYYYYYYY....',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..YYYYYYYYYYYYY...',
    '..#RRRRRRRRRRRR#..',
    '..#RWWMRRRMWWRR#..',  // logo M
    '..#RRRRRRRRRRRR#..',
    '..#RRRRRRRRRRRR#..',
    '..#RREE..EE..RR#..',  // eyes
    '..#RRRR..RRRRRR#..',
    '..#RRRR##RRRRRR#..',  // smile
    '..#RRRRRRRRRRRR#..',
    '..#RRRRRRRRRRRR#..',
    '..##############..',
    '...#..........#...',
    '...#..........#...',
    '...##........##...',
    '...##........##...',
    '...####....####...',
    '..................',
    '..................',
  ],
  [
    '...YYYYYYYYYYY....',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..YYYYYYYYYYYYY...',
    '..#RRRRRRRRRRRR#..',
    '..#RWWMRRRMWWRR#..',
    '..#RRRRRRRRRRRR#..',
    '..#RRRRRRRRRRRR#..',
    '..#RREE..EE..RR#..',
    '..#RRRR..RRRRRR#..',
    '..#RRRR##RRRRRR#..',
    '..#RRRRRRRRRRRR#..',
    '..#RRRRRRRRRRRR#..',
    '..##############..',
    '...#..........#...',
    '...#..........#...',
    '...##........##...',
    '...##........##...',
    '...####....####...',
    '..................',
    '..................',
  ],
  [
    '...YYYYYYYYYYY....',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..YYYYYYYYYYYYY...',
    '#.#RRRRRRRRRRRR#..',
    '##.RWWMRRRMWWRR#..',
    '.#.RRRRRRRRRRRR#..',
    '...RRRRRRRRRRRR#..',
    '...RREE..EE..RR#..',
    '...RRRR..RRRRRR#..',
    '...RRRR##RRRRRR#..',
    '...RRRRRRRRRRRR#..',
    '...RRRRRRRRRRRR#..',
    '..##############..',
    '...#..........#...',
    '...#..........#...',
    '...##........##...',
    '...##........##...',
    '...####....####...',
    '..................',
    '..................',
  ],
  [
    '...YYYYYYYYYYY....',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..Y.Y.Y.Y.Y.Y.Y...',
    '..YYYYYYYYYYYYY...',
    '..#RRRRRRRRRRR#.#.',
    '..#RWWMRRRMWWR.##.',
    '..#RRRRRRRRRRR#.#.',
    '..#RRRRRRRRRRR#...',
    '..#RREE..EE..R....',
    '..#RRRR..RRRRR....',
    '..#RRRR##RRRRR....',
    '..#RRRRRRRRRRR....',
    '..#RRRRRRRRRRR....',
    '..##############..',
    '...#..........#...',
    '...#..........#...',
    '...##........##...',
    '...##........##...',
    '...####....####...',
    '..................',
    '..................',
  ],
].map(rows => rows.map(W18))

// ---- SHAKE ----
const shake = [
  [
    '....WWWWWWWWWW....',
    '...WWWLLLLLLWWW...',  // dome of cream
    '...WWLLLLLLLLWW...',
    '....##########....',
    '....#WWWWWWWW#....',  // straw stick
    '....##W##W###W#...',
    '....#WWWWWWWWW#...',
    '...#WW##W##W##W#..',
    '...#WWEEWWEEWWWW#.',  // eyes
    '...#WWWWWWWWWWWW#.',
    '...#WW##WWWW##WW#.',
    '...#WWW######WWW#.',  // smile
    '...#WWWWWWWWWWWW#.',
    '....##########....',
    '......#....#......',
    '......#....#......',
    '......#....#......',
    '......##..##......',
    '.....####.####....',
    '..................',
    '..................',
    '..................',
  ],
  [
    '....WWWWWWWWWW....',
    '...WWWLLLLLLWWW...',
    '...WWLLLLLLLLWW...',
    '....##########....',
    '....#WWWWWWWW#....',
    '....##W##W###W#...',
    '....#WWWWWWWWW#...',
    '...#WW##W##W##W#..',
    '...#WWEEWWEEWWWW#.',
    '...#WWWWWWWWWWWW#.',
    '...#WW##WWWW##WW#.',
    '...#WWW######WWW#.',
    '...#WWWWWWWWWWWW#.',
    '....##########....',
    '......#....#......',
    '......#....#......',
    '......##..##......',
    '.....####.####....',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  [
    '....WWWWWWWWWW....',
    '...WWWLLLLLLWWW...',
    '...WWLLLLLLLLWW...',
    '....##########....',
    '#...#WWWWWWWW#....',
    '##..##W##W###W#...',
    '.#..#WWWWWWWWW#...',
    '...#WW##W##W##W#..',
    '...#WWEEWWEEWWWW#.',
    '...#WWWWWWWWWWWW#.',
    '...#WW##WWWW##WW#.',
    '...#WWW######WWW#.',
    '...#WWWWWWWWWWWW#.',
    '....##########....',
    '......#....#......',
    '.....##....##.....',
    '....##......##....',
    '....##......##....',
    '...####....####...',
    '..................',
    '..................',
    '..................',
  ],
  [
    '....WWWWWWWWWW....',
    '...WWWLLLLLLWWW...',
    '...WWLLLLLLLLWW...',
    '....##########....',
    '....#WWWWWWWW#...#',
    '....##W##W###W#.##',
    '....#WWWWWWWWW#.#.',
    '...#WW##W##W##W#..',
    '...#WWEEWWEEWWWW#.',
    '...#WWWWWWWWWWWW#.',
    '...#WW##WWWW##WW#.',
    '...#WWW######WWW#.',
    '...#WWWWWWWWWWWW#.',
    '....##########....',
    '......#....#......',
    '.....##....##.....',
    '....##......##....',
    '....##......##....',
    '...####....####...',
    '..................',
    '..................',
    '..................',
  ],
].map(rows => rows.map(W18))

// ---- NUGGET ----
const nugget = [
  [
    '......NNNNNN......',
    '....NNnnnnnnNN....',
    '...NnNNNNNNNNnN...',
    '..NnNNNNNNNNNNnN..',
    '..NNNEENNNNEENNN..',
    '..NNNNNNNNNNNNNN..',
    '..NnNNN####NNNnN..',
    '..NNnnNNNNNNnnNN..',
    '..NNNNNNNNNNNNNN..',
    '...NnNNNNNNNNnN...',
    '....NNnnnnnnNN....',
    '......NNNNNN......',
    '......#....#......',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
    '..................',
    '..................',
  ],
  [
    '......NNNNNN......',
    '....NNnnnnnnNN....',
    '...NnNNNNNNNNnN...',
    '..NnNNNNNNNNNNnN..',
    '..NNNEENNNNEENNN..',
    '..NNNNNNNNNNNNNN..',
    '..NnNNN####NNNnN..',
    '..NNnnNNNNNNnnNN..',
    '..NNNNNNNNNNNNNN..',
    '...NnNNNNNNNNnN...',
    '....NNnnnnnnNN....',
    '......NNNNNN......',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  [
    '......NNNNNN......',
    '....NNnnnnnnNN....',
    '...NnNNNNNNNNnN...',
    '..NnNNNNNNNNNNnN..',
    '..NNNEENNNNEENNN..',
    '..NNNNNNNNNNNNNN..',
    '..NnNNN####NNNnN..',
    '..NNnnNNNNNNnnNN..',
    '#.NNNNNNNNNNNNNN..',
    '##NnNNNNNNNNnN....',
    '.#NNnnnnnnNN......',
    '..#...NNNN........',
    '......#....#......',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
    '..................',
    '..................',
  ],
  [
    '......NNNNNN......',
    '....NNnnnnnnNN....',
    '...NnNNNNNNNNnN...',
    '..NnNNNNNNNNNNnN..',
    '..NNNEENNNNEENNN..',
    '..NNNNNNNNNNNNNN..',
    '..NnNNN####NNNnN..',
    '..NNnnNNNNNNnnNN..',
    '..NNNNNNNNNNNNNN.#',
    '...NnNNNNNNNNnN.##',
    '....NNnnnnnnNN.#..',
    '......NNNNNN......',
    '......#....#......',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
    '..................',
    '..................',
  ],
].map(rows => rows.map(W18))

// ---- ICE CREAM CONE ----
const icecream = [
  [
    '......IIIIII......',
    '....IIIIIIIIII....',
    '...IIIIIIIIIIII...',
    '..IIIIIIIiIIIIII..',
    '..IIIEEIIIIEEIII..',
    '..IIIIIIIIIIIIII..',
    '..IIIIIIIIIIIIII..',
    '..IIIII####IIIIII.',
    '..IIIIIIIIIIIIII..',
    '...IIIIIIIIIIII...',
    '....cCCCCCCCCc....',
    '....CcCCCCCCcC....',
    '....CCcCCCCcCC....',
    '.....CcCCCCcC.....',
    '......CcCCcC......',
    '......CCcCcC......',
    '.......CcCC.......',
    '........CC........',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  [
    '......IIIIII......',
    '....IIIIIIIIII....',
    '...IIIIIIIIIIII...',
    '..IIIIIIIiIIIIII..',
    '..IIIEEIIIIEEIII..',
    '..IIIIIIIIIIIIII..',
    '..IIIIIIIIIIIIII..',
    '..IIIII####IIIII..',
    '..IIIIIIIIIIIIII..',
    '...IIIIIIIIIIII...',
    '....cCCCCCCCCc....',
    '....CcCCCCCCcC....',
    '....CCcCCCCcCC....',
    '.....CcCCCCcC.....',
    '......CcCCcC......',
    '......CCcCcC......',
    '.......CcCC.......',
    '........CC........',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  [
    '...#..IIIIII......',
    '...##IIIIIIIII....',
    '....IIIIIIIIIIII..',
    '...IIIIIIIIIIIIII.',
    '...IIIEEIIIIEEII..',
    '...IIIIIIIIIIIII..',
    '...IIIIIIIIIIIII..',
    '...IIIII####IIII..',
    '...IIIIIIIIIIIII..',
    '....IIIIIIIIIII...',
    '....cCCCCCCCCc....',
    '....CcCCCCCCcC....',
    '....CCcCCCCcCC....',
    '.....CcCCCCcC.....',
    '......CcCCcC......',
    '......CCcCcC......',
    '.......CcCC.......',
    '........CC........',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
  [
    '......IIIIII...#..',
    '....IIIIIIIII.##..',
    '..IIIIIIIIIIIIII..',
    '.IIIIIIIIIIIIII...',
    '..IIIEEIIIIEEII...',
    '..IIIIIIIIIIIII...',
    '..IIIIIIIIIIIII...',
    '..IIIII####IIII...',
    '..IIIIIIIIIIIII...',
    '...IIIIIIIIIII....',
    '....cCCCCCCCCc....',
    '....CcCCCCCCcC....',
    '....CCcCCCCcCC....',
    '.....CcCCCCcC.....',
    '......CcCCcC......',
    '......CCcCcC......',
    '.......CcCC.......',
    '........CC........',
    '..................',
    '..................',
    '..................',
    '..................',
  ],
].map(rows => rows.map(W18))

// ---- CHEF (a chef hat with a face) ----
const chef = [
  [
    '....WWWWWWWWWW....',
    '...WW########WW...',
    '..WWWWWWWWWWWWWW..',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '..#############...',
    '..#PPPPPPPPPPP#...',
    '..#PPEEPPPPEEP#...',
    '..#PPPPPPPPPPPP#..',
    '..#PPPPP##PPPPP#..',
    '..#PPPP####PPPP#..',
    '..#PPPPPPPPPPPP#..',
    '..#############...',
    '......#....#......',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
  ],
  [
    '....WWWWWWWWWW....',
    '...WW########WW...',
    '..WWWWWWWWWWWWWW..',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '..#############...',
    '..#PPPPPPPPPPP#...',
    '..#PPEEPPPPEEP#...',
    '..#PPPPPPPPPPPP#..',
    '..#PPPPP##PPPPP#..',
    '..#PPPP####PPPP#..',
    '..#PPPPPPPPPPPP#..',
    '..#############...',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
    '..................',
  ],
  [
    '....WWWWWWWWWW....',
    '...WW########WW...',
    '..WWWWWWWWWWWWWW..',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '..#############...',
    '..#PPPPPPPPPPP#...',
    '..#PPEEPPPPEEP#...',
    '..#PPPPPPPPPPPP#..',
    '..#PPPPP##PPPPP#..',
    '#.#PPPP####PPPP#..',
    '##PPPPPPPPPPPPP#..',
    '.##############...',
    '......#....#......',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
  ],
  [
    '....WWWWWWWWWW....',
    '...WW########WW...',
    '..WWWWWWWWWWWWWW..',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '.WWWWWWWWWWWWWWWW.',
    '..#############...',
    '..#PPPPPPPPPPP#...',
    '..#PPEEPPPPEEP#...',
    '..#PPPPPPPPPPPP#..',
    '..#PPPPP##PPPPP#..',
    '..#PPPP####PPP#.#.',
    '..#PPPPPPPPPPPP##.',
    '..#############.#.',
    '......#....#......',
    '.....#......#.....',
    '....#........#....',
    '....#........#....',
    '.....#......#.....',
    '......##..##......',
    '.....####..####...',
    '..................',
  ],
].map(rows => rows.map(W18))

export const mascotVariants = {
  burger,
  fries,
  shake,
  nugget,
  icecream,
  chef,
}
